# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaJogo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.temporestante = QtWidgets.QProgressBar(Form)
        self.temporestante.setMaximum(180)
        self.temporestante.setProperty("value", 180)
        self.temporestante.setObjectName("temporestante")
        self.horizontalLayout.addWidget(self.temporestante)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.JogadoresSessao = QtWidgets.QLabel(Form)
        self.JogadoresSessao.setObjectName("JogadoresSessao")
        self.verticalLayout_9.addWidget(self.JogadoresSessao)
        self.listaJogadores = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listaJogadores.sizePolicy().hasHeightForWidth())
        self.listaJogadores.setSizePolicy(sizePolicy)
        self.listaJogadores.setMinimumSize(QtCore.QSize(0, 0))
        self.listaJogadores.setObjectName("listaJogadores")
        self.verticalLayout_9.addWidget(self.listaJogadores)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.letra1 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra1.sizePolicy().hasHeightForWidth())
        self.letra1.setSizePolicy(sizePolicy)
        self.letra1.setObjectName("letra1")
        self.gridLayout.addWidget(self.letra1, 0, 0, 1, 1)
        self.letra7 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra7.sizePolicy().hasHeightForWidth())
        self.letra7.setSizePolicy(sizePolicy)
        self.letra7.setObjectName("letra7")
        self.gridLayout.addWidget(self.letra7, 1, 2, 1, 1)
        self.letra8 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra8.sizePolicy().hasHeightForWidth())
        self.letra8.setSizePolicy(sizePolicy)
        self.letra8.setObjectName("letra8")
        self.gridLayout.addWidget(self.letra8, 1, 3, 1, 1)
        self.letra9 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra9.sizePolicy().hasHeightForWidth())
        self.letra9.setSizePolicy(sizePolicy)
        self.letra9.setObjectName("letra9")
        self.gridLayout.addWidget(self.letra9, 2, 0, 1, 1)
        self.letra11 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra11.sizePolicy().hasHeightForWidth())
        self.letra11.setSizePolicy(sizePolicy)
        self.letra11.setObjectName("letra11")
        self.gridLayout.addWidget(self.letra11, 2, 2, 1, 1)
        self.letra12 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra12.sizePolicy().hasHeightForWidth())
        self.letra12.setSizePolicy(sizePolicy)
        self.letra12.setObjectName("letra12")
        self.gridLayout.addWidget(self.letra12, 2, 3, 1, 1)
        self.letra13 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra13.sizePolicy().hasHeightForWidth())
        self.letra13.setSizePolicy(sizePolicy)
        self.letra13.setObjectName("letra13")
        self.gridLayout.addWidget(self.letra13, 3, 0, 1, 1)
        self.letra14 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra14.sizePolicy().hasHeightForWidth())
        self.letra14.setSizePolicy(sizePolicy)
        self.letra14.setObjectName("letra14")
        self.gridLayout.addWidget(self.letra14, 3, 1, 1, 1)
        self.letra15 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra15.sizePolicy().hasHeightForWidth())
        self.letra15.setSizePolicy(sizePolicy)
        self.letra15.setObjectName("letra15")
        self.gridLayout.addWidget(self.letra15, 3, 2, 1, 1)
        self.letra2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra2.sizePolicy().hasHeightForWidth())
        self.letra2.setSizePolicy(sizePolicy)
        self.letra2.setObjectName("letra2")
        self.gridLayout.addWidget(self.letra2, 0, 1, 1, 1)
        self.letra3 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra3.sizePolicy().hasHeightForWidth())
        self.letra3.setSizePolicy(sizePolicy)
        self.letra3.setObjectName("letra3")
        self.gridLayout.addWidget(self.letra3, 0, 2, 1, 1)
        self.letra4 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra4.sizePolicy().hasHeightForWidth())
        self.letra4.setSizePolicy(sizePolicy)
        self.letra4.setObjectName("letra4")
        self.gridLayout.addWidget(self.letra4, 0, 3, 1, 1)
        self.letra5 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra5.sizePolicy().hasHeightForWidth())
        self.letra5.setSizePolicy(sizePolicy)
        self.letra5.setObjectName("letra5")
        self.gridLayout.addWidget(self.letra5, 1, 0, 1, 1)
        self.letra6 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra6.sizePolicy().hasHeightForWidth())
        self.letra6.setSizePolicy(sizePolicy)
        self.letra6.setObjectName("letra6")
        self.gridLayout.addWidget(self.letra6, 1, 1, 1, 1)
        self.letra10 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra10.sizePolicy().hasHeightForWidth())
        self.letra10.setSizePolicy(sizePolicy)
        self.letra10.setObjectName("letra10")
        self.gridLayout.addWidget(self.letra10, 2, 1, 1, 1)
        self.letra16 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letra16.sizePolicy().hasHeightForWidth())
        self.letra16.setSizePolicy(sizePolicy)
        self.letra16.setObjectName("letra16")
        self.gridLayout.addWidget(self.letra16, 3, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Pontuacao = QtWidgets.QLabel(Form)
        self.Pontuacao.setObjectName("Pontuacao")
        self.verticalLayout_2.addWidget(self.Pontuacao)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pontosEdit = QtWidgets.QLabel(Form)
        self.pontosEdit.setObjectName("pontosEdit")
        self.horizontalLayout_7.addWidget(self.pontosEdit)
        self.points = QtWidgets.QLabel(Form)
        self.points.setObjectName("points")
        self.horizontalLayout_7.addWidget(self.points)
        spacerItem3 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listaPalavrasEncontradas = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listaPalavrasEncontradas.sizePolicy().hasHeightForWidth())
        self.listaPalavrasEncontradas.setSizePolicy(sizePolicy)
        self.listaPalavrasEncontradas.setMinimumSize(QtCore.QSize(0, 260))
        self.listaPalavrasEncontradas.setObjectName("listaPalavrasEncontradas")
        self.verticalLayout_2.addWidget(self.listaPalavrasEncontradas)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.inputjogador = QtWidgets.QTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputjogador.sizePolicy().hasHeightForWidth())
        self.inputjogador.setSizePolicy(sizePolicy)
        self.inputjogador.setMinimumSize(QtCore.QSize(200, 10))
        self.inputjogador.setSizeIncrement(QtCore.QSize(0, 0))
        self.inputjogador.setBaseSize(QtCore.QSize(0, 0))
        self.inputjogador.setAutoFillBackground(False)
        self.inputjogador.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inputjogador.setObjectName("inputjogador")
        self.horizontalLayout_6.addWidget(self.inputjogador)
        self.btnenviar = QtWidgets.QPushButton(Form)
        self.btnenviar.setObjectName("btnenviar")
        self.horizontalLayout_6.addWidget(self.btnenviar)
        spacerItem5 = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.regraPont = QtWidgets.QTextEdit(Form)
        self.regraPont.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.regraPont.setUndoRedoEnabled(False)
        self.regraPont.setReadOnly(True)
        self.regraPont.setObjectName("regraPont")
        self.verticalLayout.addWidget(self.regraPont)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.sair = QtWidgets.QPushButton(Form)
        self.sair.setObjectName("sair")
        self.horizontalLayout_4.addWidget(self.sair)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "                                                                                      LOGOMARCA JOGO"))
        self.temporestante.setFormat(_translate("Form", "%p segundos"))
        self.JogadoresSessao.setText(_translate("Form", "   Jogadores da Sessão"))
        self.letra1.setText(_translate("Form", "A"))
        self.letra7.setText(_translate("Form", "G"))
        self.letra8.setText(_translate("Form", "H"))
        self.letra9.setText(_translate("Form", "I"))
        self.letra11.setText(_translate("Form", "K"))
        self.letra12.setText(_translate("Form", "L"))
        self.letra13.setText(_translate("Form", "M"))
        self.letra14.setText(_translate("Form", "N"))
        self.letra15.setText(_translate("Form", "O"))
        self.letra2.setText(_translate("Form", "B"))
        self.letra3.setText(_translate("Form", "C"))
        self.letra4.setText(_translate("Form", "D"))
        self.letra5.setText(_translate("Form", "E"))
        self.letra6.setText(_translate("Form", "F"))
        self.letra10.setText(_translate("Form", "J"))
        self.letra16.setText(_translate("Form", "P"))
        self.Pontuacao.setText(_translate("Form", "                PONTUAÇÃO"))
        self.pontosEdit.setText(_translate("Form", "0"))
        self.points.setText(_translate("Form", "pontos"))
        self.label_3.setText(_translate("Form", " PALAVRAS ENCONTRADAS"))
        self.btnenviar.setText(_translate("Form", "ENVIAR"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.regraPont.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">REGRAS DE PONTUAÇÃO</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ef2929;\">3 Letras - 1 Ponto</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#3465a4;\">4 Letras - 4 Pontos</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#8ae234;\">5 ou mais Letras - 6 Pontos</span></p></body></html>"))
        self.sair.setText(_translate("Form", "SAIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

